import type { Model } from "@earendil-works/pi-ai";
import { GEMINI_CLI_API } from "./gemini-cli-provider.ts";

export const GEMINI_CLI_MODELS: Model<typeof GEMINI_CLI_API>[] = [
  {
    id: "gemini-2.0-flash",
    name: "Gemini 2.0 Flash (Cloud Code Assist)",
    api: GEMINI_CLI_API,
    provider: "google-gemini-cli",
    baseUrl: "https://cloudcode-pa.googleapis.com",
    reasoning: false,
    input: ["text", "image"],
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 1048576,
    maxTokens: 8192,
  },
  {
    id: "gemini-2.5-flash",
    name: "Gemini 2.5 Flash (Cloud Code Assist)",
    api: GEMINI_CLI_API,
    provider: "google-gemini-cli",
    baseUrl: "https://cloudcode-pa.googleapis.com",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 1048576,
    maxTokens: 65535,
  },
  {
    id: "gemini-2.5-pro",
    name: "Gemini 2.5 Pro (Cloud Code Assist)",
    api: GEMINI_CLI_API,
    provider: "google-gemini-cli",
    baseUrl: "https://cloudcode-pa.googleapis.com",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 1048576,
    maxTokens: 65535,
  },
  {
    id: "gemini-3-flash-preview",
    name: "Gemini 3 Flash Preview (Cloud Code Assist)",
    api: GEMINI_CLI_API,
    provider: "google-gemini-cli",
    baseUrl: "https://cloudcode-pa.googleapis.com",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 1048576,
    maxTokens: 65535,
  },
  {
    id: "gemini-3-pro-preview",
    name: "Gemini 3 Pro Preview (Cloud Code Assist)",
    api: GEMINI_CLI_API,
    provider: "google-gemini-cli",
    baseUrl: "https://cloudcode-pa.googleapis.com",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 1048576,
    maxTokens: 65535,
  },
  {
    id: "gemini-3.1-flash-lite-preview",
    name: "Gemini 3.1 Flash Lite Preview (Cloud Code Assist)",
    api: GEMINI_CLI_API,
    provider: "google-gemini-cli",
    baseUrl: "https://cloudcode-pa.googleapis.com",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 1048576,
    maxTokens: 65535,
  },
  {
    id: "gemini-3.1-pro-preview",
    name: "Gemini 3.1 Pro Preview (Cloud Code Assist)",
    api: GEMINI_CLI_API,
    provider: "google-gemini-cli",
    baseUrl: "https://cloudcode-pa.googleapis.com",
    reasoning: true,
    input: ["text", "image"],
    cost: {
      input: 0,
      output: 0,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 1048576,
    maxTokens: 65535,
  },
];
